added Allocation Chart
polywrap/polyfolio pull request #56
Opened 2022-03-08 11:53 UTC by yuliiagorgozka

2022-03-08 11:54 UTC, yuliiagorgozka commented
https://github.com/polywrap/polyfolio/issues/52

2022-03-08 14:16 UTC, DmitriyIvchenko requested changes

2022-03-08 14:16 UTC, DmitriyIvchenko commented on src/common/components/Button1D/Button1D.tsx
> +      1D <MenuArrow className={styles.arrow} filled startPosition={'up'} />
1D? what does it mean?

2022-03-08 20:12 UTC, yuliiagorgozka commented on src/common/components/Button1D/Button1D.tsx
> +      1D <MenuArrow className={styles.arrow} filled startPosition={'up'} />
Repeated 1D button in all tables. I can just call it something else.

2022-03-11 11:49 UTC, DmitriyIvchenko commented on src/common/components/Button1D/Button1D.tsx
> +      1D <MenuArrow className={styles.arrow} filled startPosition={'up'} />
but it is not button 1D it is table date range selector

2022-03-11 11:50 UTC, DmitriyIvchenko commented on src/common/components/Button1D/Button1D.tsx
> +      1D <MenuArrow className={styles.arrow} filled startPosition={'up'} />
also 1 **day / week / month / year** should be moved to translations

2022-03-11 11:51 UTC, yuliiagorgozka commented on src/common/components/Button1D/Button1D.tsx
> +      1D <MenuArrow className={styles.arrow} filled startPosition={'up'} />
Now I will throw a commit, and rename

2022-03-11 15:32 UTC, DmitriyIvchenko approved these changes

2022-03-11 21:54 UTC, merged