Network page #47
polywrap/polyfolio pull request #64
Opened 2022-03-10 21:11 UTC by Iangyl

https://github.com/polywrap/polyfolio/issues/47

2022-03-11 08:30 UTC, DmitriyIvchenko requested changes

2022-03-11 08:30 UTC, DmitriyIvchenko commented on src/App.tsx
> +            />
same pages?

so I can be one route with path={[RoutePath.Protocol, RoutePath.Network]}

2022-03-11 08:30 UTC, DmitriyIvchenko commented on src/common/components/VaultsTable/Vaults.module.scss
> +    width: calc(100% / 3) !important;
please don't use important

2022-03-11 08:30 UTC, DmitriyIvchenko commented on src/pages/NetworkNProtocolsPage/NetworkNProtocolsPage.tsx
> +              icon={path === 'network'
Please don't use strings 

move to ENUMS

2022-03-11 08:30 UTC, DmitriyIvchenko commented on src/pages/NetworkNProtocolsPage/NetworkNProtocolsPage.tsx
> +              title={path === 'network'
Please don't use strings 

move to ENUMS

2022-03-11 08:30 UTC, DmitriyIvchenko commented on src/pages/NetworkNProtocolsPage/NetworkNProtocolsPage.tsx
> +                : 'Aave Protocol'
translations

2022-03-11 08:30 UTC, DmitriyIvchenko commented on src/pages/NetworkNProtocolsPage/NetworkNProtocolsPage.tsx
> +                ? `${translation.Networks.eth} Network`
translations

2022-03-11 08:30 UTC, DmitriyIvchenko commented on src/pages/NetworkNProtocolsPage/NetworkNProtocolsPage.tsx
> +              path === 'network' ? (
Please don't use strings 

move to ENUMS

2022-03-11 08:30 UTC, DmitriyIvchenko commented on src/pages/NetworkNProtocolsPage/NetworkNProtocolsPage.tsx
> +              secondaryTitle=''
empty string?

use this parameter as optional

2022-03-11 08:30 UTC, DmitriyIvchenko commented on src/common/components/VaultsTable/VaultsTableItem/VaultsTableItem.types.ts
> +  id?: number;
why all parameters are optional?

2022-03-11 08:30 UTC, DmitriyIvchenko commented on src/common/components/VaultsTable/VaultsTable.tsx
> +      <HeaderTable title="Vaults" sum={9337337.0} />
translations

2022-03-11 08:30 UTC, DmitriyIvchenko commented on src/common/components/HeaderPageInfo/HeaderPageInfo.types.ts
> +  percent?: number;
why all parameters are optional?

2022-03-11 10:34 UTC, Iangyl commented on src/pages/NetworkNProtocolsPage/NetworkNProtocolsPage.tsx
> +                : 'Aave Protocol'
These names are primary, are they needed to translate?

2022-03-12 19:10 UTC, DmitriyIvchenko approved these changes

2022-03-13 15:05 UTC, merged