Refactoring and adding a button for shrinking tables
polywrap/polyfolio pull request #65
Opened 2022-03-12 13:32 UTC by yuliiagorgozka

2022-03-12 19:14 UTC, DmitriyIvchenko requested changes

2022-03-12 19:14 UTC, DmitriyIvchenko commented on src/common/components/AssetAllocationChart/AssetAllocationChart.tsx
> +      <div className={classNames(styles.title_container, {[styles.none]: tableIsOpen})}>
maybe hidden will be better an class name

2022-03-12 19:14 UTC, DmitriyIvchenko commented on src/common/components/ProtocolsTable/ProtocolsTable.tsx
> +        title="Protocols"
move to translations

2022-03-12 19:14 UTC, DmitriyIvchenko commented on src/common/components/AssetsTable/AssetsTable.tsx
> +        title="Assets"
move to tranlations

2022-03-15 07:52 UTC, DmitriyIvchenkoYozmaTech approved these changes

2022-03-15 07:52 UTC, merged