Transactions
polywrap/polyfolio pull request #89
Opened 2022-04-13 13:26 UTC by Iangyl

Closes: https://github.com/polywrap/polyfolio/issues/94

2022-04-20 12:46 UTC, DmitriyIvchenko requested changes

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/AssetTransaction/useTransactions.ts
> +  console.log(state);
remove

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/AssetsTable/AssetsTable.tsx
> +        sum={preparedData['allAssetsSum']}
1. what is preparedData? maybe assetTableData?

2. why not preparedData. allAssetsSum

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/AssetsTable/AssetsTable.tsx
> +  const preparedData = formatedData();
same here

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/AssetsTable/AssetsTableItem/AssetsTableItem.types.ts
>    link?: string;
why items are optional?

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/HeaderDashboard/HeaderDashboard.tsx
> +          <h2>${numberFormatter({value: preparedData['allAssetsSum'], size: 2})}</h2>
same

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/HeaderDashboard/HeaderDashboard.tsx
> +  const preparedData = formatedData();
same

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/HeaderDashboard/HeaderDashboard.types.ts
> +  percent?: string;
same

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/HeaderGasInfoMenu/HeaderGasInfoMenu.types.ts
>    isExternal?: boolean;
same

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/Networks/Networks.config.ts
> +  if (preparedData['balance']) {
what is this preparedData['balance']? why not preparedData.balance?

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/Networks/Networks.config.ts
> +  const preparedData = formateData();
same

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/Networks/Networks.config.ts
> +        allAssets = _.flatten([...allAssets, ...ejectAssetsFromProtocol(protocol)]);
different methods?

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/Networks/Networks.config.ts
> +      _.forEach(preparedData['balance'][item.name]?.protocols, protocol => {
what is preparedData['balance'][item.name]? where is types?

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/Networks/Networks.config.ts
> +      let allAssets = [];
I can't understand why do we need this?

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/PerformanceTable/PerformanceItem.types.ts
> +  secondaryTitlePercent?: string;
same

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/Profile/Profile.tsx
> +  const preparedData = formatedData();
same

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/VaultsTable/VaultsTable.tsx
> +  const preparedData = formateData();
same

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/VaultsTable/VaultsTable.tsx
> +        sum={preparedData['allAssetsSum']}
same

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/VaultsTable/VaultsTableItem/VaultsTableItem.config.ts
> +  const preparedData = formateData();
same

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/components/VaultsTable/VaultsTableItem/VaultsTableItem.config.ts
> +  return _.map(preparedData['allAssets'], asset => {
same

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/hooks/useBalance/useBalance.ts
> +      uri: `ens/rinkeby/mock.defiwrapper.eth`,
move to config

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/hooks/useGetData/useGetData.ts
> +  const formateData = () => {
https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/hooks/useTransaction/useTransaction.ts
> +          uri: "ens/rinkeby/ethereum.token.resolvers.defiwrapper.eth",
move to config

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/hooks/useTransaction/useTransaction.ts
> +        currency: 'USD',
is this correct? why not currency from picker?

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/common/hooks/useTransaction/useTransaction.ts
> +        console.log(transactions)
remove

2022-04-20 12:46 UTC, DmitriyIvchenko commented on src/utils/dataFormating.ts
> +      _.round(Number(rmCommasFromNum(value['token'].values[0].value)), 2)
value.token

2022-04-20 19:33 UTC, Iangyl commented on src/common/hooks/useTransaction/useTransaction.ts
> +          uri: "ens/rinkeby/ethereum.token.resolvers.defiwrapper.eth",
what config do you mean?

2022-04-20 20:04 UTC, Iangyl commented on src/utils/dataFormating.ts
> +      _.round(Number(rmCommasFromNum(value['token'].values[0].value)), 2)
does not exist on property unknown

2022-04-24 07:29 UTC, DmitriyIvchenko approved these changes

2022-04-26 09:12 UTC, merged